version: "3"

services:
  pyro-app:
    build:
      context: .
      dockerfile: deployments/Dockerfile.app
    command: /opt/pyro/service /opt/pyro/public
    ports:
      - "8080:8080"
  pyro-nginx:
    build:
      context: .
      dockerfile: deployments/Dockerfile.nginx
    ports:
      - "8081:80"
